Fix Clang warnings
Gegel85/osumap-parser pull request #2
Opened 2021-01-21 14:10 UTC by staticssleever668

If you merge this after #1, a merge commit is probably not going to appear

2021-07-07 11:04 UTC, staticssleever668 commented
@Gegel85.

2021-07-07 11:45 UTC, Gegel85 commented
I think it needs %zu for all strlen calls too because it returns a size_t too and on windows it is either unsigned int in 32bits or unsigned long long in 64bits.

2021-07-11 10:51 UTC, staticssleever668 commented
@Gegel85, yeah, you are right. This time I also went ahead and fixed clang-tidy warnings (the only warning left is about `strerror` function being thread-unsafe).

2021-07-12 01:10 UTC, Gegel85 requested changes
I marked all the spots that probably should be zu too (though I'm not sure)

2021-07-12 01:10 UTC, PinkySmile commented on src/osu_map_parser.c
> +		sprintf(error_buffer, "Memory allocation error (%luB)", 2 * sizeof(*array));
That is supposed to be %zu

2021-07-12 01:10 UTC, PinkySmile commented on src/osu_map_parser.c
> +			sprintf(error_buffer, "Memory allocation error (%luB)", sizeof(*categories));
I think that too

2021-07-12 01:10 UTC, PinkySmile commented on src/osu_map_parser.c
> +			sprintf(error_buffer, "Memory allocation error (%luB)", (i - start + 1) * sizeof(*categories[currentIndex].lines));
Here

2021-07-12 01:10 UTC, Gegel85 commented on src/osu_map_parser.c
> +				sprintf(err_buffer, "Memory allocation error (%luB)", result.length * sizeof(*result.content));
zu

2021-07-12 01:10 UTC, Gegel85 commented on src/osu_map_parser.c
> +	vector.y = (int)OsuMap_getInteger(elems[1], 0, 0, err_buffer, jump_buffer);
I think the cleaner fix would be to change the type for the vectors to be longs instead

2021-07-12 01:10 UTC, Gegel85 commented on src/osu_map_parser.c
> +		sprintf(err_buffer, "Memory allocation error (%luB)", array.length * sizeof(*array.content));
zu too probably

2021-07-12 01:10 UTC, Gegel85 commented on src/osu_map_parser.c
> +			sprintf(err_buffer, "Memory allocation error (%luB)", OsuMap_getStringArraySize(nbr) + 1);
zu

2021-07-12 01:10 UTC, Gegel85 commented on src/osu_map_parser.c
> +				sprintf(err_buffer, "Memory allocation error (%luB)", (OsuMap_getStringArraySize(nbr) + 1) * sizeof(*infos.edgeAdditions));
zu

2021-07-12 01:10 UTC, Gegel85 commented on src/osu_map_parser.c
> +			sprintf(err_buffer, "Memory allocation error (%luB)", sizeof(OsuMap_hitObjectSliderInfos));
zu

2021-07-12 01:10 UTC, Gegel85 commented on src/osu_map_parser.c
> +			sprintf(err_buffer, "Memory allocation error (%luB)", sizeof(unsigned long));
zu

2021-07-12 01:10 UTC, Gegel85 commented on src/osu_map_parser.c
> +		sprintf(err_buffer, "Memory allocation error (%luB)", elements.length * sizeof(*elements.content));
zu

2021-07-12 01:10 UTC, Gegel85 commented on src/osu_map_parser.c
> +		sprintf(err_buffer, "Memory allocation error (%luB)", elements.length * sizeof(*elements.content));
zu

2021-07-12 01:10 UTC, Gegel85 commented on src/osu_map_parser.c
> +		sprintf(err_buffer, "Memory allocation error (%luB)", elements.length * sizeof(*elements.content));
zu

2021-07-12 01:10 UTC, Gegel85 commented
Btw, how did you get here ? x)

2021-07-14 12:43 UTC, staticssleever668 commented
@Gegel85, hi, thanks for the review! I fixed those as well.

I came here by searching osu! parsers in GitHub. I needed one in C/C++ and didn't want to write it by myself at the time, and this one looked the most promising.

2021-07-14 15:17 UTC, Gegel85 reviewed
Everything seems fine. I'll just pull the submodule in my replay player just to check if it didn't break anything relevent before merging.

2021-07-14 20:29 UTC, Gegel85 requested changes
You just forgot to rename a struct. Besides that, everything seems fine and ready for merge.

2021-07-14 20:29 UTC, Gegel85 commented on include/osu_map_parser.h
>  typedef struct OsuIntegerVectorArray {
You forgot to change it here x)

2021-07-15 06:48 UTC, staticssleever668 commented on include/osu_map_parser.h
>  typedef struct OsuIntegerVectorArray {
Fixed.

2021-07-28 10:23 UTC, Gegel85 approved these changes

2021-07-28 10:23 UTC, Gegel85 commented
All good ! Thanks for helping !

2021-07-28 10:23 UTC, merged